### PR TITLE
feat(init): handle firewall rules

### PR DESCRIPTION
**Pull request by 1715173329**
Hi, please make a runtime test before merging this PR, thanks.

### CODE REVIEW

**Comment by Zxilly** [comment]
@1715173329 I'm sorry for taking so long to reply, I was busy with final exams.
I don't think hard-coding firewall rules is a good idea. For example, WeChat will use http protocol on port 443 with ua `mmtls/***`. This can sometimes lead to be checked. I think manually configuring the firewall rules will give the user a better understanding of the mechanics of `ua2f`'s operation.
And I alse made some updates on the main branch, could you please also resolve the conflict?

**Comment by 1715173329** [comment]
> @1715173329 I'm sorry for taking so long to reply, I was busy with final exams.

Never mind, and I wish you all the best in your exam ;)

> I don't think hard-coding firewall rules is a good idea. For example, WeChat will use http protocol on port 443 with ua `mmtls/***`. This can sometimes lead to be checked. Users must decide for themselves whether to expend additional computing power to handle port 443 for such exceptions.
> I think manually configuring the firewall rules will give the user a better understanding of the mechanics of `ua2f`'s operation.
> And I alse made some updates on the main branch, could you please also resolve the conflict?

There's nothing to be conflicted and vsm

**Comment by 1715173329** [comment]
> @1715173329 I'm sorry for taking so long to reply, I was busy with final exams.

Never mind, and I wish you all the best in your exam :)

> I don't think hard-coding firewall rules is a good idea. For example, WeChat will use http protocol on port 443 with ua `mmtls/***`. This can sometimes lead to be checked. Users must decide for themselves whether to expend additional computing power to handle port 443 for such exceptions.

We can make a option to let users decide whether to handle traffic on port 443, so it doesn't matter.

> I think manually configuring the firewall rules will give the user a better understanding of the mechanics of `ua2f`'s operation.

Correct, but it's fine to have some out-of-the-box rules.
They can be made as an option as well.

**Comment by 1715173329** [comment]
@Zxilly Sorry but fw is not my area, so if we need to handle 443 traffic, should I mark it as 44 like this or simply remove the "RETURN" line?
```sh
iptables -t mangle -A ua2f -p tcp --dport 443 -j CONNMARK --set-mark 44
```

**Comment by Zxilly** [comment]
@1715173329 `44` means always try to replace the UA string. No rule is just OK.

**Comment by 1715173329** [comment]
> @1715173329 `44` means always try to replace the UA string. No rule is just OK.

Thank you, I just updated the rules, please make a review ;)

**Review by Zxilly — APPROVED** [review]
lgtm

**Comment by Zxilly** [comment]
@1715173329 Could you please write a short introduction on the config and setup of current version ua2f? I didn't familiar with uci, and some user reported unexpected behavior.

**Comment by 1715173329** [comment]
> Could you please write a short introduction on the config and setup of current version ua2f?

- Set `enable` to `1` means starting the daemon.
- Set `handle_fw` to `1` means appending the fw rules
- Set `handle_tls` to `1` means processing the traffic on 443 port as well
 requires `handle_fw` to be enabled first

**Comment by Zxilly** [comment]
@1715173329 I mean the correspond shell command to operate on these argument.

**Comment by 1715173329** [comment]
> @1715173329 I mean the correspond shell command to operate on these argument.

You can modify the config via vim/nano etc. directly and call `service ua2f start` to start.

Or configure it via `uci`:
```bash
# Enable the daemon
uci set ua2f.enabled.enabled=1
# At your option set fw rules
uci set ua2f.firewall.handle_fw=1
uci set ua2f.firewall.handle_tls=1
# Apply your modifications
uci commit ua2f
# Start the daemon
service ua2f start
```

**Comment by Zxilly** [comment]
@1715173329 Thanks!

**Comment by 1715173329** [comment]
> @1715173329 Thanks!

It's my pleasure ;)

**Pull request merged**
