### PR TITLE
feat(init): ua2f auto start

### PR DESCRIPTION
**Pull request by SunBK201**
ua2f auto start

### CODE REVIEW

**Review by Zxilly — APPROVED** [review]

**Comment by 1715173329** [comment]
However this is against with the default behavior of service files on OpenWrt.
People who want to use it should enable it by theirselves.

It can be a optional feature, when someone packed it into a firmware, and share the firmware to others, you know, not everyone need it.
Also, it requires a available network connection when setting firewall rules, which is almost impossible at the first run, that I mean, when someone flashes a new firmware for their router, they actually needs to setup the network firstly before running it.

Your configurations won't be lost when you're doing a upgrade (unless you have selected "don't keep configurations" manually), so it's fine to disable it by default.

**Comment by Zxilly** [comment]
@1715173329 I agree with you

**Comment by Zxilly** [comment]
@SunBK201 @1715173329 I will later update readme to introduce this action to new user.

**Comment by SunBK201** [comment]
agree

**Pull request merged**
